### PR TITLE
Add service definition files for koserver

### PR DESCRIPTION
**Pull request by Hzj-jie**
It covers kosync, nginx and nightswatcher.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-misc/45)

### CODE REVIEW

**Comment by Hzj-jie** [comment]
This change is ready for review now.

**Comment by Frenzie** [comment]
It could be an idea to also include some of the run/restart scripts insofar as they don't leak anything of import. (The biggest thing to avoid is the signing key, anything else?)

**Comment by Hzj-jie** [comment]
What's the signing key?

**Comment by Frenzie** [comment]
It's used in nightswatcher to sign the Android APKs. It's simply in with all the other important stuff under build. :-)

**Pull request merged**
